version: '3'

services:
  db:
    image: postgres
    ports: 
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    env_file:
        - ./.env
  hunter-searcher:
    build: .
    container_name: hunter-searcher
    ports:
      - "22002:22001"
    depends_on:
      - db
    env_file:
      - ./.env

volumes:
  postgres_data:
