version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data 
    env_file:
        - ./.env
  hunter-searcher:
    build: .
    container_name: hunter-searcher
    ports:
      - "22001:22001"
    depends_on:
      - db
    env_file:
      - ./.env

volumes:
  postgres_data:
